import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
          {
            key: "Content-Security-Policy",
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com",
              "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
              "font-src 'self' https://fonts.gstatic.com",
              "img-src 'self' data: https:",
              "connect-src 'self' https://www.google-analytics.com https://analytics.google.com",
              "frame-ancestors 'self'",
            ].join("; "),
          },
        ],
      },
    ];
  },

  async redirects() {
    // 301 redirects: year-slug URLs → clean URLs
    const businessSlugs = [
      "best-accounting-firms-singapore",
      "best-aesthetic-clinics-singapore",
      "best-aircon-cleaning-singapore",
      "best-aircon-servicing-singapore",
      "best-airport-transfer-singapore",
      "best-audit-firms-singapore",
      "best-bakeries-singapore",
      "best-bhutan-travel-agencies-singapore",
      "best-breakfast-singapore",
      "best-brunch-cafes-singapore",
      "best-bubble-tea-singapore",
      "best-car-workshops-singapore",
      "best-catering-services-singapore",
      "best-chauffeur-service-singapore",
      "best-chicken-rice-singapore",
      "best-childcare-singapore",
      "best-chiropractor-singapore",
      "best-coffee-shops-singapore",
      "best-commercial-cleaning-singapore",
      "best-cooking-classes-singapore",
      "best-corporate-lawyers-singapore",
      "best-corporate-limousine-singapore",
      "best-dentists-singapore",
      "best-dermatologist-singapore",
      "best-digital-marketing-agencies-singapore",
      "best-dim-sum-singapore",
      "best-divorce-lawyers-singapore",
      "best-dog-groomers-singapore",
      "best-electricians-singapore",
      "best-english-tuition-singapore",
      "best-eye-specialist-singapore",
      "best-florists-singapore",
      "best-food-in-katong",
      "best-gp-clinic-singapore",
      "best-gyms-singapore",
      "best-hair-salons-singapore",
      "best-halal-restaurants-singapore",
      "best-hawker-food-singapore",
      "best-home-cleaning-services-singapore",
      "best-home-renovation-singapore",
      "best-insurance-agencies-singapore",
      "best-interior-design-companies-singapore",
      "best-italian-restaurant-singapore",
      "best-korean-bbq-singapore",
      "best-limo-rental-singapore",
      "best-limousine-service-singapore",
      "best-luxury-airport-transfer-singapore",
      "best-luxury-car-hire-singapore",
      "best-luxury-hotels-singapore",
      "best-maid-agencies-singapore",
      "best-massage-spa-singapore",
      "best-math-tuition-singapore",
      "best-metal-roof-canopy-singapore",
      "best-monthly-chauffeur-service-singapore",
      "best-mortgage-brokers-singapore",
      "best-moving-companies-singapore",
      "best-nail-salons-singapore",
      "best-nature-based-preschools-singapore",
      "best-orthodontist-singapore",
      "best-personal-trainers-singapore",
      "best-pest-control-singapore",
      "best-photography-studios-singapore",
      "best-physiotherapists-singapore",
      "best-pizza-singapore",
      "best-plastic-surgeons-singapore",
      "best-plumbers-singapore",
      "best-prata-singapore",
      "best-premium-limousine-singapore",
      "best-primary-school-tuition-singapore",
      "best-private-chauffeur-singapore",
      "best-preschools-singapore",
      "best-property-agents-singapore",
      "best-ramen-singapore",
      "best-renovation-contractor-singapore",
      "best-roof-contractors-singapore",
      "best-roof-leak-repair-singapore",
      "best-roof-waterproofing-singapore",
      "best-science-tuition-singapore",
      "best-seafood-restaurants-singapore",
      "best-secondary-school-tuition-singapore",
      "best-security-systems-singapore",
      "best-seo-agency-singapore",
      "best-seo-company-singapore",
      "best-solar-companies-singapore",
      "best-sushi-singapore",
      "best-swimming-lessons-singapore",
      "best-tcm-singapore",
      "best-thai-food-singapore",
      "best-tuition-centres-singapore",
      "best-vegetarian-restaurants-singapore",
      "best-web-design-companies-singapore",
      "best-website-development-companies-singapore",
      "best-wedding-car-rental-singapore",
      "best-yoga-studios-singapore",
      "best-zi-char-singapore",
    ];

    const businessRedirects = businessSlugs.map((slug) => ({
      source: `/business/${slug}-2026`,
      destination: `/business/${slug}`,
      permanent: true,
    }));

    return [
      ...businessRedirects,
      // Bhutan travel moved from business to travel category
      {
        source: "/business/best-bhutan-travel-agency-2026",
        destination: "/travel/best-bhutan-travel-agency",
        permanent: true,
      },
      // Preschool location pages (filename suffix differs from slug)
      {
        source: "/business/best-preschools-bukit-timah-2026",
        destination: "/business/best-preschools-bukit-timah-singapore",
        permanent: true,
      },
      {
        source: "/business/best-preschools-katong-2026",
        destination: "/business/best-preschools-katong-singapore",
        permanent: true,
      },
      // Tech slug cleanup
      {
        source: "/tech/best-laptops-2024",
        destination: "/tech/best-laptops",
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
